### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ron208888**
hi teacher, I'm 陳與任.
please review my work, thank you!

http://52.9.222.2:3000/
http://52.9.222.2:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout in small to middle devices is obviously broken.
52 9 222 2_3000_attraction_2

**Comment by ron208888** [comment]
I fixed the problem. thank you a lot!

http://52.9.222.2:3000/
http://52.9.222.2:3000/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
Better, but still miner issues:
1. Size of radio button. Border style of button.
2. Image slider should extend to full width in mobile version.
52 9 222 2_3000_attraction_3

**Comment by ron208888** [comment]
hi teacher, I fixed those problems.
please review my work, thank you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

You can try to use Flask Blueprint to seperate API routes from app.py

**Pull request merged**
