### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ron208888**
Hello teacher, I'm 陳與任.
Please check my code of this week.
Thank you very much!
link: http://52.9.222.2:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Layout in 360px ~ 1200px devices will break. We should handle them.
2. Left padding of keyword input should not be 0.

**Comment by ron208888** [comment]
Hi teacher, I fixed problems.
Please check my code, thanks a lot.

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your code will load the same page multiple times if we scroll down and up quickly.

**Comment by ron208888** [comment]
sorry teacher, I don't understand the problem, 
image
my code is working normally, please explain more for me, thank you for the trouble.

**Comment by cwpeng** [comment]
Try testing online URL shown below:

https://user-images.githubusercontent.com/6104683/204123336-3acdc20f-f8e0-47d1-9049-f9681fef47b7.mp4

**Comment by ron208888** [comment]
hi teacher, I found the problem you talked about when I ran my code on Safari(but it's still normal on Chrome).
so I try little change and now it can fit Safari. though I noticed that you use Chrome to test.
please review my work again, thanks!

**Review by cwpeng — CHANGES_REQUESTED** [review]
Issue is still there and I think it's not browser dependent.

未命名-2

**Comment by ron208888** [comment]
sorry teacher, I'm not careful enough so made this problem. I finally understood the issue and fixed it.
please review my work again, thank you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
